SCHEMA_VERSION = "1.0.0"
GENERATOR_VERSION = "scenario-report-generator/0.1.0"
SITE_BASE = "https://pablof7z.github.io/podcast-player/"

SECTION_TO_DIMENSION = {
    "flow": "flow",
    "attempted_test": "attempted_test",
    "scenario_setup": "scenario_setup",
    "expected_behavior": "expected_behavior",
    "actual_result": "actual_result",
    "artifacts": "artifacts",
    "review_skill_grounding": "review_skill_grounding",
    "ui_polish_report": "ui_polish",
    "ux_polish_report": "ux_polish",
    "performance_metrics": "performance",
    "accessibility_dynamic_type": "accessibility_dynamic_type",
    "liquid_glass_ios_primitives": "liquid_glass_ios_primitives",
    "error_recovery_behavior": "error_recovery",
    "privacy_security": "privacy_security",
    "nmp_architecture_cohesiveness": "nmp_architecture",
    "product_coherence_in_context": "product_coherence",
    "regression_risk": "regression_risk",
    "defects_issues_filed": "defects_issues_filed",
    "verdict": "verdict",
    "next_actions": "next_actions",
    "cross_screen_continuity": "cross_screen_continuity",
    "states_resilience": "states_resilience",
    "touch_ergonomics": "touch_ergonomics",
    "motion_haptics": "motion_haptics",
    "information_architecture": "information_architecture",
    "content_hierarchy": "content_hierarchy",
    "observability": "observability",
    "analytics_privacy_boundaries": "analytics_privacy_boundaries",
    "replayability_cassette_provenance": "replayability_cassette_provenance",
    "evidence_confidence": "evidence_confidence",
    "device_os_matrix": "device_os_matrix",
    "sister_app_nmp_chirp_comparison": "sister_app_nmp_chirp_comparison",
}

SECTION_LABELS = {
    "flow": "Flow",
    "attempted_test": "Attempted Test",
    "scenario_setup": "Scenario Setup",
    "expected_behavior": "Expected Behavior",
    "actual_result": "Actual Result",
    "artifacts": "Artifacts, Screenshots, Video",
    "review_skill_grounding": "Review Skill Grounding",
    "ui_polish_report": "UI Polish Report",
    "ux_polish_report": "UX Polish Report",
    "performance_metrics": "Performance Metrics",
    "accessibility_dynamic_type": "Accessibility And Dynamic Type",
    "liquid_glass_ios_primitives": "Liquid Glass And iOS Primitives",
    "error_recovery_behavior": "Error And Recovery Behavior",
    "privacy_security": "Privacy And Security",
    "nmp_architecture_cohesiveness": "NMP Architecture And Cohesiveness",
    "product_coherence_in_context": "Product Coherence In Context",
    "regression_risk": "Regression Risk",
    "defects_issues_filed": "Defects And Issues Filed",
    "verdict": "Verdict",
    "next_actions": "Next Actions",
    "cross_screen_continuity": "Cross-Screen Continuity",
    "states_resilience": "Empty, Loading, Offline, And Recovery States",
    "touch_ergonomics": "Touch Ergonomics",
    "motion_haptics": "Motion And Haptics",
    "information_architecture": "Information Architecture",
    "content_hierarchy": "Content Hierarchy",
    "observability": "Observability",
    "analytics_privacy_boundaries": "Analytics And Privacy Boundaries",
    "replayability_cassette_provenance": "Replayability And Cassette Provenance",
    "evidence_confidence": "Evidence Confidence",
    "device_os_matrix": "Device And OS Matrix",
    "sister_app_nmp_chirp_comparison": "Sister App, NMP, And Chirp Comparison",
}

GROUPS = {
    "functional_correctness": [
        "flow",
        "attempted_test",
        "scenario_setup",
        "expected_behavior",
        "actual_result",
        "error_recovery",
        "regression_risk",
    ],
    "evidence_reproducibility": [
        "artifacts",
        "review_skill_grounding",
        "replayability_cassette_provenance",
        "device_os_matrix",
        "evidence_confidence",
        "defects_issues_filed",
    ],
    "product_experience": [
        "ui_polish",
        "ux_polish",
        "liquid_glass_ios_primitives",
        "cross_screen_continuity",
        "states_resilience",
        "touch_ergonomics",
        "motion_haptics",
        "information_architecture",
        "content_hierarchy",
        "product_coherence",
    ],
    "engineering_quality": [
        "performance",
        "accessibility_dynamic_type",
        "privacy_security",
        "nmp_architecture",
        "observability",
        "analytics_privacy_boundaries",
    ],
    "follow_through": [
        "defects_issues_filed",
        "verdict",
        "next_actions",
    ],
}

SKILL_GROUNDING = [
    {
        "name": "vabole/apple-skills@ios-liquid-glass",
        "search_terms": "liquid glass iOS primitives",
        "coverage": "Liquid Glass restraint, Reduce Transparency behavior, system chrome, and iOS 26 visual primitives.",
    },
    {
        "name": "vabole/apple-skills@hig",
        "search_terms": "Apple HIG iOS",
        "coverage": "Apple platform controls, navigation, typography, accessibility, and native interaction expectations.",
    },
    {
        "name": "phazurlabs/ux-ui-mastery@Mobile UX Design",
        "search_terms": "mobile UX design",
        "coverage": "Task clarity, cognitive load, thumb ergonomics, interruption recovery, and mobile flow cohesion.",
    },
    {
        "name": "nmp-app-architecture",
        "search_terms": "NMP architecture Rust core thin shell",
        "coverage": "Rust-owned state and policy, bounded FFI/projections, privacy fail-closed behavior, and replayable clocks.",
    },
]
