SCHEMA_VERSION = "1.1.0"
GENERATOR_VERSION = "scenario-report-generator/0.5.0"
SITE_BASE = "https://pablof7z.github.io/podcast-player/"
SKILL_SEARCH_QUERY = "UI UX mobile Liquid Glass design review accessibility"

SECTION_TO_DIMENSION = {
    "persona_job_acceptance": "persona_acceptance",
    "flow": "flow",
    "attempted_test": "attempted_test",
    "scenario_setup": "scenario_setup",
    "execution_attempts": "execution_attempts",
    "expected_behavior": "expected_behavior",
    "actual_result": "actual_result",
    "artifacts": "artifacts",
    "evidence_provenance": "evidence_provenance",
    "review_skill_grounding": "review_skill_grounding",
    "ui_polish_report": "ui_polish",
    "ux_polish_report": "ux_polish",
    "performance_metrics": "performance",
    "accessibility_dynamic_type": "accessibility_dynamic_type",
    "liquid_glass_ios_primitives": "liquid_glass_ios_primitives",
    "error_recovery_behavior": "error_recovery",
    "privacy_security": "privacy_security",
    "nmp_architecture_cohesiveness": "nmp_architecture",
    "product_coherence_in_context": "product_coherence",
    "product_cluster_coherence": "product_cluster_coherence",
    "before_after_deltas": "before_after_deltas",
    "reliability_flakiness": "reliability_flakiness",
    "regression_risk": "regression_risk",
    "defects_issues_filed": "defects_issues_filed",
    "revalidation_status": "revalidation_status",
    "risks_follow_up": "risks_follow_up",
    "instrumentation_gaps": "instrumentation_gaps",
    "localization_content_quality": "localization_content_quality",
    "controls_gestures_audio": "controls_gestures_audio",
    "offline_resume_behavior": "offline_resume_behavior",
    "readiness_gates": "readiness_gates",
    "verdict": "verdict",
    "next_actions": "next_actions",
    "owner_status": "owner_status",
    "data_integrity_state_sync": "data_integrity_state_sync",
    "navigation_state_restoration": "navigation_state_restoration",
    "device_viewport_coverage": "device_viewport_coverage",
    "media_session_background_continuity": "media_session_background_continuity",
    "cross_screen_continuity": "cross_screen_continuity",
    "states_resilience": "states_resilience",
    "touch_ergonomics": "touch_ergonomics",
    "motion_haptics": "motion_haptics",
    "information_architecture": "information_architecture",
    "content_hierarchy": "content_hierarchy",
    "observability": "observability",
    "analytics_privacy_boundaries": "analytics_privacy_boundaries",
    "replayability_cassette_provenance": "replayability_cassette_provenance",
    "evidence_confidence": "evidence_confidence",
    "device_os_matrix": "device_os_matrix",
    "sister_app_nmp_chirp_comparison": "sister_app_nmp_chirp_comparison",
}

SECTION_LABELS = {
    "persona_job_acceptance": "Persona, Job, And Acceptance Criteria",
    "flow": "Flow",
    "attempted_test": "Attempted Test",
    "scenario_setup": "Scenario Setup",
    "execution_attempts": "Execution Attempts, Retries, And Branches",
    "expected_behavior": "Expected Behavior",
    "actual_result": "Actual Result",
    "artifacts": "Artifacts, Screenshots, Video",
    "evidence_provenance": "Evidence Provenance",
    "review_skill_grounding": "Review Skill Grounding",
    "ui_polish_report": "UI Polish Report",
    "ux_polish_report": "UX Polish Report",
    "performance_metrics": "Performance Metrics",
    "accessibility_dynamic_type": "Accessibility And Dynamic Type",
    "liquid_glass_ios_primitives": "Liquid Glass And iOS Primitives",
    "error_recovery_behavior": "Error And Recovery Behavior",
    "privacy_security": "Privacy And Security",
    "nmp_architecture_cohesiveness": "NMP Architecture And Cohesiveness",
    "product_coherence_in_context": "Product Coherence In Context",
    "product_cluster_coherence": "Product Cluster Coherence",
    "before_after_deltas": "Before/After Deltas",
    "reliability_flakiness": "Reliability And Flakiness",
    "regression_risk": "Regression Risk",
    "defects_issues_filed": "Defects And Issues Filed",
    "revalidation_status": "Revalidation Status",
    "risks_follow_up": "Risks, Follow-Up, And Back-Links",
    "instrumentation_gaps": "Instrumentation Gaps And Missing Evidence",
    "localization_content_quality": "Localization And Content Quality",
    "controls_gestures_audio": "Controls, Gestures, Audio, And Haptics",
    "offline_resume_behavior": "Offline, Interruption, And Resume Behavior",
    "readiness_gates": "Readiness Gates",
    "verdict": "Verdict",
    "next_actions": "Next Actions",
    "owner_status": "Owner And Status",
    "data_integrity_state_sync": "Data Integrity And State Sync",
    "navigation_state_restoration": "Navigation State And Restoration",
    "device_viewport_coverage": "Device, Viewport, And Generated-Page Coverage",
    "media_session_background_continuity": "Media Session And Background Audio Continuity",
    "cross_screen_continuity": "Cross-Screen Continuity",
    "states_resilience": "Empty, Loading, Offline, And Recovery States",
    "touch_ergonomics": "Touch Ergonomics",
    "motion_haptics": "Motion And Haptics",
    "information_architecture": "Information Architecture",
    "content_hierarchy": "Content Hierarchy",
    "observability": "Observability",
    "analytics_privacy_boundaries": "Analytics And Privacy Boundaries",
    "replayability_cassette_provenance": "Replayability And Cassette Provenance",
    "evidence_confidence": "Evidence Confidence",
    "device_os_matrix": "Device And OS Matrix",
    "sister_app_nmp_chirp_comparison": "Sister App, NMP, And Chirp Comparison",
}

GROUPS = {
    "functional_correctness": [
        "persona_acceptance",
        "flow",
        "attempted_test",
        "scenario_setup",
        "execution_attempts",
        "expected_behavior",
        "actual_result",
        "error_recovery",
        "offline_resume_behavior",
        "data_integrity_state_sync",
        "navigation_state_restoration",
        "regression_risk",
    ],
    "evidence_reproducibility": [
        "artifacts",
        "evidence_provenance",
        "review_skill_grounding",
        "replayability_cassette_provenance",
        "device_os_matrix",
        "device_viewport_coverage",
        "evidence_confidence",
        "instrumentation_gaps",
        "defects_issues_filed",
    ],
    "product_experience": [
        "ui_polish",
        "ux_polish",
        "liquid_glass_ios_primitives",
        "cross_screen_continuity",
        "states_resilience",
        "touch_ergonomics",
        "before_after_deltas",
        "media_session_background_continuity",
        "motion_haptics",
        "information_architecture",
        "content_hierarchy",
        "product_coherence",
        "product_cluster_coherence",
        "localization_content_quality",
        "controls_gestures_audio",
        "readiness_gates",
    ],
    "engineering_quality": [
        "performance",
        "accessibility_dynamic_type",
        "privacy_security",
        "nmp_architecture",
        "observability",
        "analytics_privacy_boundaries",
        "reliability_flakiness",
    ],
    "follow_through": [
        "defects_issues_filed",
        "revalidation_status",
        "risks_follow_up",
        "verdict",
        "next_actions",
        "owner_status",
    ],
}

SKILL_GROUNDING = [
    {
        "selected": True,
        "name": "casper-studios/casper-marketplace@liquid-glass",
        "search_terms": SKILL_SEARCH_QUERY,
        "coverage": "Search result with 283 installs. Loaded with npx skills use; grounds content-first Liquid Glass, glass-only navigation/control chrome, adaptive tinting, 8 pt spacing, 44 pt hit targets, SF Symbols, and Reduce Motion/Transparency expectations.",
    },
    {
        "selected": True,
        "name": "charleswiltgen/axiom@axiom-design",
        "search_terms": SKILL_SEARCH_QUERY,
        "coverage": "Loaded from the charleswiltgen/axiom search result (221 installs). Grounds HIG, semantic colors, SF typography, Liquid Glass variant discipline, SF Symbols, platform navigation, and app composition checks.",
    },
    {
        "selected": True,
        "name": "charleswiltgen/axiom@axiom-accessibility",
        "search_terms": SKILL_SEARCH_QUERY,
        "coverage": "Loaded from the charleswiltgen/axiom search result (221 installs). Grounds VoiceOver labels, Dynamic Type, contrast, touch targets, Reduce Motion, Reduce Transparency, dismiss traps, dead ends, missing states, and gesture alternatives.",
    },
    {
        "selected": True,
        "name": "charleswiltgen/axiom@axiom-performance",
        "search_terms": SKILL_SEARCH_QUERY,
        "coverage": "Loaded from the charleswiltgen/axiom search result (221 installs). Grounds measured performance review, launch/tap/screen-settle latency, scroll hitches, memory, CPU, energy, and measurement-before-optimization discipline.",
    },
    {
        "selected": True,
        "name": "phazurlabs/ux-ui-mastery@mobile ux design",
        "search_terms": SKILL_SEARCH_QUERY,
        "coverage": "Search result with 96 installs. Loaded with npx skills use; grounds mobile-first UX, one primary action per screen, thumb-zone reachability, interruption/resume behavior, visible gesture alternatives, 44 pt targets, 8 pt spacing, and latency-as-UX budgets.",
    },
    {
        "selected": False,
        "name": "openai/plugins@swiftui-liquid-glass",
        "search_terms": SKILL_SEARCH_QUERY,
        "coverage": "Search result with 59 installs. npx skills use could not resolve swiftui-liquid-glass from this package in this environment; exact hit was cited but not used as loaded grounding.",
    },
    {
        "selected": False,
        "name": "ravnhq/ai-toolkit@liquid-glass-ios",
        "search_terms": SKILL_SEARCH_QUERY,
        "coverage": "Search result with 29 installs. Considered but not loaded because higher-install Liquid Glass and Axiom/HIG skills covered the template needs.",
    },
    {
        "selected": False,
        "name": "simota/agent-skills@native",
        "search_terms": SKILL_SEARCH_QUERY,
        "coverage": "Search result with 21 installs. Considered but not loaded because it was less directly tied to iOS UI/UX evidence gates than the selected skills.",
    },
    {
        "selected": False,
        "name": "local NMP architecture doctrine",
        "search_terms": "NMP architecture Rust core thin shell",
        "coverage": "Represented in NMP architecture dimensions: Rust-owned state and policy, bounded FFI/projections, privacy fail-closed behavior, and replayable clocks.",
    },
]

QUALITY_AREAS = {
    "ui": "Layout, spacing, typography, visual hierarchy, semantic color, SF Symbols, screenshots, and platform-native finish.",
    "ux": "Task clarity, user effort, feedback, interruption recovery, cognitive load, and route predictability.",
    "performance": "Launch, interaction latency, screen-settle time, scroll hitches, memory, CPU, audio, network, and provider latency.",
    "accessibility": "VoiceOver, Dynamic Type, contrast, Reduce Motion, Reduce Transparency, 44 pt targets, captions, and assistive navigation.",
    "reliability": "Rerun count, flake history, retry behavior, stale evidence, timeout behavior, and deterministic replay.",
    "privacy_security": "Secrets, private keys, permissions, logs, analytics, relay visibility, cassette redaction, and export safety.",
    "content_localization": "Podcast metadata, transcript/agent copy, truncation, empty copy, locale/date/number behavior, and translation safety.",
    "controls_gestures": "Buttons, menus, sheets, gestures, audio route controls, haptics, keyboard alternatives, and touch reach.",
    "offline_resume": "Offline state, app relaunch, background playback, interrupted provider calls, downloads, and resume from stale state.",
    "observability": "Structured logs, metric IDs, provider/request IDs, relay IDs, redacted traces, and issue reproduction context.",
}

READINESS_GATES = {
    "required_evidence": "Screenshots/UI trees/logs/cassettes/metrics required by the scenario are attached and redacted.",
    "skill_grounding": "UI, UX, accessibility, performance, and product judgments cite the loaded review skills or local doctrine.",
    "score_integrity": "Every dimension and group score follows the evidence gates and matches the final verdict.",
    "product_coherence": "Individual scenario judgment and related-scenario group judgment are both present.",
    "defect_tracking": "Every actionable defect has severity, owner, GitHub issue link, and fix/revalidation state.",
    "release_readiness": "No blocker or major unresolved risk remains without an explicit owner and acceptance rationale.",
}
