import Foundation

// MARK: - Chapter collection helper

extension BidirectionalCollection where Element == Episode.Chapter {
    /// Returns the chapter that contains `playheadSeconds` — the last chapter
    /// whose `startTime <= playheadSeconds`. Falls back to the first chapter
    /// when the playhead sits before any chapter starts (typical at t=0
    /// before playback begins) so consumers always have an active indicator
    /// instead of a phantom none-selected state.
    func active(at playheadSeconds: TimeInterval) -> Episode.Chapter? {
        if let hit = self.last(where: { $0.startTime <= playheadSeconds }) {
            return hit
        }
        return self.first
    }
}

// MARK: - Podcasting 2.0 substructs

extension Episode {
    /// A chapter marker. Either inline (parsed from a `<podcast:chapter>`-like
    /// element) or hydrated later from `chaptersURL` JSON.
    struct Chapter: Codable, Sendable, Hashable, Identifiable {
        var id: UUID
        /// Start time in seconds from the beginning of the episode.
        var startTime: TimeInterval
        /// Optional end time. When `nil`, chapter ends at the next chapter or EOF.
        var endTime: TimeInterval?
        var title: String
        /// Optional `img` URL from Podcasting 2.0 chapters JSON.
        var imageURL: URL?
        /// Optional `url` reference (publisher show notes link).
        var linkURL: URL?
        /// `toc=false` chapters are non-navigable (e.g. ad markers).
        var includeInTableOfContents: Bool
        /// `true` when the chapter was synthesised by `AIChapterCompiler`
        /// from the transcript rather than parsed from a publisher source.
        /// Defaults to `false`; the player surfaces a subtle "AI" tag for true.
        var isAIGenerated: Bool
        /// 1–2 sentence summary of the chapter, generated by `AIChapterCompiler`
        /// alongside the chapter boundaries (or attached to publisher chapters in
        /// a follow-up enrichment pass). `nil` until enrichment runs.
        var summary: String?
        /// UUID string of the source episode when this chapter corresponds to a
        /// clip from another episode (e.g. an agent-generated TTS episode with
        /// snippet turns). Drives the clip-source chip in `PlayerView` and the
        /// mid-play artwork swap.
        var sourceEpisodeID: String?

        init(
            id: UUID = UUID(),
            startTime: TimeInterval,
            endTime: TimeInterval? = nil,
            title: String,
            imageURL: URL? = nil,
            linkURL: URL? = nil,
            includeInTableOfContents: Bool = true,
            isAIGenerated: Bool = false,
            summary: String? = nil,
            sourceEpisodeID: String? = nil
        ) {
            self.id = id
            self.startTime = startTime
            self.endTime = endTime
            self.title = title
            self.imageURL = imageURL
            self.linkURL = linkURL
            self.includeInTableOfContents = includeInTableOfContents
            self.isAIGenerated = isAIGenerated
            self.summary = summary
            self.sourceEpisodeID = sourceEpisodeID
        }

        private enum CodingKeys: String, CodingKey {
            case id, startTime, endTime, title, imageURL, linkURL
            case includeInTableOfContents, isAIGenerated, summary, sourceEpisodeID
        }

        init(from decoder: Decoder) throws {
            let c = try decoder.container(keyedBy: CodingKeys.self)
            id = try c.decode(UUID.self, forKey: .id)
            startTime = try c.decode(TimeInterval.self, forKey: .startTime)
            endTime = try c.decodeIfPresent(TimeInterval.self, forKey: .endTime)
            title = try c.decodeIfPresent(String.self, forKey: .title) ?? ""
            imageURL = try c.decodeIfPresent(URL.self, forKey: .imageURL)
            linkURL = try c.decodeIfPresent(URL.self, forKey: .linkURL)
            includeInTableOfContents = try c.decodeIfPresent(Bool.self, forKey: .includeInTableOfContents) ?? true
            isAIGenerated = try c.decodeIfPresent(Bool.self, forKey: .isAIGenerated) ?? false
            summary = try c.decodeIfPresent(String.self, forKey: .summary)
            sourceEpisodeID = try c.decodeIfPresent(String.self, forKey: .sourceEpisodeID)
        }
    }

    /// `<podcast:person>` — host / guest / cohost / etc.
    /// See podcasting2.org/docs/podcast-namespace/tags/person.
    struct Person: Codable, Sendable, Hashable, Identifiable {
        var id: UUID
        /// Display name (element text).
        var name: String
        /// `role` attribute: host, guest, cohost, …. Stored verbatim
        /// (case-insensitive); lower-cased for comparison.
        var role: String?
        /// `group` attribute (e.g. cast, writing). Optional.
        var group: String?
        /// `img` attribute — headshot URL.
        var imageURL: URL?
        /// `href` attribute — link to the person's homepage / social.
        var linkURL: URL?

        init(
            id: UUID = UUID(),
            name: String,
            role: String? = nil,
            group: String? = nil,
            imageURL: URL? = nil,
            linkURL: URL? = nil
        ) {
            self.id = id
            self.name = name
            self.role = role
            self.group = group
            self.imageURL = imageURL
            self.linkURL = linkURL
        }
    }

    /// `<podcast:soundbite>` — a short, publisher-curated highlight clip.
    struct SoundBite: Codable, Sendable, Hashable, Identifiable {
        var id: UUID
        /// `startTime` attribute, seconds.
        var startTime: TimeInterval
        /// `duration` attribute, seconds.
        var duration: TimeInterval
        /// Optional element text — a human-friendly title.
        var title: String?

        init(
            id: UUID = UUID(),
            startTime: TimeInterval,
            duration: TimeInterval,
            title: String? = nil
        ) {
            self.id = id
            self.startTime = startTime
            self.duration = duration
            self.title = title
        }
    }

    /// A detected ad span inside the audio. Produced by `AIChapterCompiler`
    /// from the transcript and persisted on the episode so the player can
    /// auto-skip (gated by `Settings.autoSkipAds`) and the chapter rail can
    /// flag overlapping chapters with the amber stripe.
    struct AdSegment: Codable, Sendable, Hashable, Identifiable {
        var id: UUID
        /// Start of the ad in seconds from the beginning of the episode.
        var start: TimeInterval
        /// End of the ad in seconds. Always greater than `start`.
        var end: TimeInterval
        /// Where in the episode this ad sits — pre-roll, mid-roll, or
        /// post-roll. Drives the "Skip 30s ad" pre-roll affordance.
        var kind: AdKind

        init(
            id: UUID = UUID(),
            start: TimeInterval,
            end: TimeInterval,
            kind: AdKind
        ) {
            self.id = id
            self.start = start
            self.end = end
            self.kind = kind
        }

        private enum CodingKeys: String, CodingKey {
            case id, start, end, kind
        }

        init(from decoder: Decoder) throws {
            let c = try decoder.container(keyedBy: CodingKeys.self)
            id = try c.decodeIfPresent(UUID.self, forKey: .id) ?? UUID()
            start = try c.decode(TimeInterval.self, forKey: .start)
            end = try c.decode(TimeInterval.self, forKey: .end)
            kind = try c.decodeIfPresent(AdKind.self, forKey: .kind) ?? .midroll
        }
    }

    /// Classification for an `AdSegment`. `preroll` ads anchor the
    /// "Skip 30s ad" button above the scrubber; `midroll` is the common
    /// case; `postroll` segments are flagged but don't drive the pre-roll UI.
    enum AdKind: String, Codable, Sendable, Hashable, CaseIterable {
        case preroll
        case midroll
        case postroll
    }

    /// Records where an agent-generated episode was commissioned from.
    /// Stored on the episode so the player can surface a tappable source link.
    enum GenerationSource: Sendable, Equatable, Hashable {
        case inAppChat(conversationID: UUID)
        case nostr(rootEventID: String, peerPubkeyHex: String)
    }
}

// MARK: - Episode.GenerationSource Codable

extension Episode.GenerationSource: Codable {
    private enum CodingKeys: String, CodingKey {
        case type, conversationID, rootEventID, peerPubkeyHex
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        let type = try c.decode(String.self, forKey: .type)
        switch type {
        case "inAppChat":
            let id = try c.decode(UUID.self, forKey: .conversationID)
            self = .inAppChat(conversationID: id)
        case "nostr":
            let rootEventID = try c.decode(String.self, forKey: .rootEventID)
            let peerPubkeyHex = try c.decode(String.self, forKey: .peerPubkeyHex)
            self = .nostr(rootEventID: rootEventID, peerPubkeyHex: peerPubkeyHex)
        default:
            throw DecodingError.dataCorrupted(.init(
                codingPath: [CodingKeys.type],
                debugDescription: "Unknown GenerationSource type: \(type)"
            ))
        }
    }

    func encode(to encoder: Encoder) throws {
        var c = encoder.container(keyedBy: CodingKeys.self)
        switch self {
        case .inAppChat(let conversationID):
            try c.encode("inAppChat", forKey: .type)
            try c.encode(conversationID, forKey: .conversationID)
        case .nostr(let rootEventID, let peerPubkeyHex):
            try c.encode("nostr", forKey: .type)
            try c.encode(rootEventID, forKey: .rootEventID)
            try c.encode(peerPubkeyHex, forKey: .peerPubkeyHex)
        }
    }
}
