import Foundation

/// LLM-derived grouping that covers a slice of the user's subscription
/// library. Generated by `PodcastCategorizationService` and persisted on
/// `AppState.categories`. Later UX (per-category settings, smart playlists)
/// reads back through `AppStateStore` lookup helpers — see
/// `AppStateStore+Categories.swift` and `AppStateStore+CategorySettings.swift`.
struct PodcastCategory: Codable, Sendable, Hashable, Identifiable {
    /// Stable local identifier minted at generation time. Deliberately
    /// independent of the model's text so renaming a category doesn't
    /// collide with existing per-category settings keyed off `id`.
    var id: UUID
    /// Human-friendly display name produced by the model
    /// (e.g. "Technology Deep-Dives").
    var name: String
    /// Lowercased, hyphenated form of `name` suitable for routing or
    /// per-category preference keys. Echoed by the model and validated
    /// before persisting.
    var slug: String
    /// One short sentence the model wrote describing what belongs here.
    var description: String
    /// Optional tint hint for Liquid-Glass surfaces. Stored as a
    /// `#RRGGBB` / `#RRGGBBAA` string so the SwiftUI layer can convert
    /// lazily without coupling the domain type to UI frameworks.
    var colorHex: String?
    /// Subscriptions the model placed in this category. Validation
    /// guarantees every UUID resolves to a real subscription at the
    /// time of generation.
    var subscriptionIDs: [UUID]
    /// Wall-clock time of the run that produced this entry. The set of
    /// categories shares a single `generatedAt` per recompute; preserved
    /// here so a later UI can show "generated 3 days ago" per row.
    var generatedAt: Date
    /// Identifier of the model that produced the response, e.g.
    /// `"anthropic/claude-sonnet-4-6"`. Optional — the response may
    /// omit it, in which case we fall back to the requested model.
    var model: String?

    init(
        id: UUID = UUID(),
        name: String,
        slug: String,
        description: String = "",
        colorHex: String? = nil,
        subscriptionIDs: [UUID] = [],
        generatedAt: Date = Date(),
        model: String? = nil
    ) {
        self.id = id
        self.name = name
        self.slug = slug
        self.description = description
        self.colorHex = colorHex
        self.subscriptionIDs = subscriptionIDs
        self.generatedAt = generatedAt
        self.model = model
    }

    private enum CodingKeys: String, CodingKey {
        case id, name, slug, description, colorHex
        case subscriptionIDs, generatedAt, model
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id = try c.decode(UUID.self, forKey: .id)
        name = try c.decodeIfPresent(String.self, forKey: .name) ?? ""
        slug = try c.decodeIfPresent(String.self, forKey: .slug) ?? ""
        description = try c.decodeIfPresent(String.self, forKey: .description) ?? ""
        colorHex = try c.decodeIfPresent(String.self, forKey: .colorHex)
        subscriptionIDs = try c.decodeIfPresent([UUID].self, forKey: .subscriptionIDs) ?? []
        generatedAt = try c.decodeIfPresent(Date.self, forKey: .generatedAt) ?? Date()
        model = try c.decodeIfPresent(String.self, forKey: .model)
    }
}
