// automatically generated by the FlatBuffers compiler, do not modify

package podcastr.projection;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class PodcastProjectionJsonFrame extends com.google.flatbuffers.Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static PodcastProjectionJsonFrame getRootAsPodcastProjectionJsonFrame(ByteBuffer _bb) { return getRootAsPodcastProjectionJsonFrame(_bb, new PodcastProjectionJsonFrame()); }
  public static PodcastProjectionJsonFrame getRootAsPodcastProjectionJsonFrame(ByteBuffer _bb, PodcastProjectionJsonFrame obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public static boolean PodcastProjectionJsonFrameBufferHasIdentifier(ByteBuffer _bb) { return __has_identifier(_bb, "PJPR"); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PodcastProjectionJsonFrame __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long schemaVersion() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public String json() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer jsonAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer jsonInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createPodcastProjectionJsonFrame(FlatBufferBuilder builder,
      long schemaVersion,
      int jsonOffset) {
    builder.startTable(2);
    PodcastProjectionJsonFrame.addJson(builder, jsonOffset);
    PodcastProjectionJsonFrame.addSchemaVersion(builder, schemaVersion);
    return PodcastProjectionJsonFrame.endPodcastProjectionJsonFrame(builder);
  }

  public static void startPodcastProjectionJsonFrame(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addSchemaVersion(FlatBufferBuilder builder, long schemaVersion) { builder.addInt(0, (int) schemaVersion, (int) 0L); }
  public static void addJson(FlatBufferBuilder builder, int jsonOffset) { builder.addOffset(1, jsonOffset, 0); }
  public static int endPodcastProjectionJsonFrame(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 6);  // json
    return o;
  }
  public static void finishPodcastProjectionJsonFrameBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset, "PJPR"); }
  public static void finishSizePrefixedPodcastProjectionJsonFrameBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset, "PJPR"); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PodcastProjectionJsonFrame get(int j) { return get(new PodcastProjectionJsonFrame(), j); }
    public PodcastProjectionJsonFrame get(PodcastProjectionJsonFrame obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}
