//! Rust-owned generated TTS episode metadata planner.
//!
//! Swift still executes native/cloud capabilities: ElevenLabs synthesis,
//! AVFoundation duration loading, snippet-file resolution, and audio stitching.
//! This FFI owns the semantic product derivation from those raw facts: chapter
//! grouping, fallback labels, transcript segments, flat transcript text, and
//! inherited artwork selection.

use std::ffi::{c_char, CStr, CString};

use serde::{Deserialize, Serialize};

use crate::ffi::guard::ffi_guard;
use crate::ffi::handle::PodcastHandle;

const DEFAULT_ELEVEN_LABS_VOICE_ID: &str = "21m00Tcm4TlvDq8ikWAM";
const DEFAULT_AGENT_GENERATED_PODCAST_ID: &str = "A6E17000-0000-4000-A000-A6E17EDA7E12";

#[derive(Debug, Deserialize)]
struct GeneratedEpisodePlanRequest {
    turns: Vec<GeneratedTurn>,
}

#[derive(Debug, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
enum GeneratedTurn {
    Speech {
        text: String,
        duration_secs: f64,
    },
    Snippet {
        episode_id: String,
        start_seconds: f64,
        duration_secs: f64,
        label: Option<String>,
        source_episode_title: Option<String>,
        image_url: Option<String>,
    },
}

#[derive(Debug, Serialize)]
struct GeneratedEpisodePlan {
    chapters: Vec<GeneratedChapter>,
    transcript_segments: Vec<GeneratedTranscriptSegment>,
    transcript_text: String,
    inherited_artwork_url: Option<String>,
}

#[derive(Debug, Serialize)]
struct GeneratedChapter {
    start_secs: f64,
    title: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    image_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    source_episode_id: Option<String>,
}

#[derive(Debug, Serialize)]
struct GeneratedTranscriptSegment {
    start: f64,
    end: f64,
    text: String,
}

#[no_mangle]
#[allow(clippy::not_unsafe_ptr_arg_deref)]
pub extern "C" fn nmp_app_podcast_agent_tts_episode_plan(
    handle: *mut PodcastHandle,
    request_json: *const c_char,
) -> *mut c_char {
    if handle.is_null() || request_json.is_null() {
        return err_json("null argument").into_raw();
    }
    ffi_guard(
        "nmp_app_podcast_agent_tts_episode_plan",
        || err_json("panic").into_raw(),
        || {
            let json_str = match unsafe { CStr::from_ptr(request_json) }.to_str() {
                Ok(s) => s,
                Err(_) => return err_json("invalid UTF-8").into_raw(),
            };
            let req: GeneratedEpisodePlanRequest = match serde_json::from_str(json_str) {
                Ok(r) => r,
                Err(e) => return err_json(&format!("JSON parse: {e}")).into_raw(),
            };
            ok_json(&serde_json::json!({ "result": build_plan(req.turns) })).into_raw()
        },
    )
}

#[no_mangle]
#[allow(clippy::not_unsafe_ptr_arg_deref)]
pub extern "C" fn nmp_app_podcast_agent_tts_default_voice(
    handle: *mut PodcastHandle,
) -> *mut c_char {
    if handle.is_null() {
        return err_json("null argument").into_raw();
    }
    ffi_guard(
        "nmp_app_podcast_agent_tts_default_voice",
        || err_json("panic").into_raw(),
        || {
            let h = unsafe { &*handle };
            let voice_id = h
                .state
                .library
                .store
                .lock()
                .ok()
                .and_then(|s| {
                    let configured = s.eleven_labs_voice_id().trim();
                    if configured.is_empty() {
                        None
                    } else {
                        Some(configured.to_owned())
                    }
                })
                .unwrap_or_else(|| DEFAULT_ELEVEN_LABS_VOICE_ID.to_owned());
            ok_json(&serde_json::json!({ "result": { "voice_id": voice_id } })).into_raw()
        },
    )
}

#[no_mangle]
#[allow(clippy::not_unsafe_ptr_arg_deref)]
pub extern "C" fn nmp_app_podcast_agent_generated_podcast_descriptor(
    handle: *mut PodcastHandle,
) -> *mut c_char {
    if handle.is_null() {
        return err_json("null argument").into_raw();
    }
    ffi_guard(
        "nmp_app_podcast_agent_generated_podcast_descriptor",
        || err_json("panic").into_raw(),
        || {
            ok_json(&serde_json::json!({
                "result": {
                    "podcast_id": DEFAULT_AGENT_GENERATED_PODCAST_ID,
                    "title": "Agent Generated",
                    "description": "Episodes generated by your AI agent.",
                    "author": "Podcast Agent",
                    "visibility": "private",
                    "title_is_placeholder": false,
                    "categories": []
                }
            }))
            .into_raw()
        },
    )
}

fn build_plan(turns: Vec<GeneratedTurn>) -> GeneratedEpisodePlan {
    let mut chapters = Vec::new();
    let mut transcript_segments = Vec::new();
    let mut cursor = 0.0;
    let mut speech_start: Option<f64> = None;
    let mut speech_texts: Vec<String> = Vec::new();

    for turn in turns {
        match turn {
            GeneratedTurn::Speech {
                text,
                duration_secs,
            } => {
                let text = text.trim().to_owned();
                let duration = positive_duration(duration_secs);
                if !text.is_empty() {
                    if speech_start.is_none() {
                        speech_start = Some(cursor);
                    }
                    speech_texts.push(text.clone());
                    transcript_segments.push(GeneratedTranscriptSegment {
                        start: cursor,
                        end: cursor + duration,
                        text,
                    });
                }
                cursor += duration;
            }
            GeneratedTurn::Snippet {
                episode_id,
                start_seconds,
                duration_secs,
                label,
                source_episode_title,
                image_url,
            } => {
                flush_speech_chapter(&mut chapters, &mut speech_start, &mut speech_texts);
                let duration = positive_duration(duration_secs);
                let label = clean_opt(label);
                let title = label
                    .clone()
                    .or_else(|| clean_opt(source_episode_title))
                    .unwrap_or_else(|| quote_title(start_seconds));
                chapters.push(GeneratedChapter {
                    start_secs: cursor,
                    title,
                    image_url: clean_opt(image_url),
                    source_episode_id: clean_opt(Some(episode_id)),
                });
                if let Some(text) = label {
                    transcript_segments.push(GeneratedTranscriptSegment {
                        start: cursor,
                        end: cursor + duration,
                        text,
                    });
                }
                cursor += duration;
            }
        }
    }

    flush_speech_chapter(&mut chapters, &mut speech_start, &mut speech_texts);
    let inherited_artwork_url = chapters.iter().find_map(|c| c.image_url.clone());
    let transcript_text = transcript_segments
        .iter()
        .map(|s| s.text.as_str())
        .collect::<Vec<_>>()
        .join(" ");

    GeneratedEpisodePlan {
        chapters,
        transcript_segments,
        transcript_text,
        inherited_artwork_url,
    }
}

fn flush_speech_chapter(
    chapters: &mut Vec<GeneratedChapter>,
    speech_start: &mut Option<f64>,
    speech_texts: &mut Vec<String>,
) {
    if speech_texts.is_empty() {
        return;
    }
    let Some(start) = speech_start.take() else {
        speech_texts.clear();
        return;
    };
    let combined = speech_texts.join(" ");
    chapters.push(GeneratedChapter {
        start_secs: start,
        title: speech_chapter_title(&combined),
        image_url: None,
        source_episode_id: None,
    });
    speech_texts.clear();
}

fn speech_chapter_title(text: &str) -> String {
    const LIMIT: usize = 60;
    if text.chars().count() <= LIMIT {
        return text.to_owned();
    }
    let preview: String = text.chars().take(LIMIT).collect();
    format!("{preview}...")
}

fn quote_title(start_seconds: f64) -> String {
    let secs = if start_seconds.is_finite() && start_seconds > 0.0 {
        start_seconds as i64
    } else {
        0
    };
    format!("Quote at {}:{:02}", secs / 60, secs % 60)
}

fn positive_duration(seconds: f64) -> f64 {
    if seconds.is_finite() && seconds > 0.0 {
        seconds
    } else {
        0.0
    }
}

fn clean_opt(value: Option<String>) -> Option<String> {
    value.map(|s| s.trim().to_owned()).filter(|s| !s.is_empty())
}

fn ok_json(value: &serde_json::Value) -> CString {
    CString::new(value.to_string()).unwrap_or_else(|_| err_json("serialization"))
}

fn err_json(message: &str) -> CString {
    CString::new(serde_json::json!({ "error": message }).to_string())
        .unwrap_or_else(|_| CString::new("{\"error\":\"serialization\"}").unwrap())
}
