//! Action types for the knowledge layer.
//!
//! [`IngestChunks`] is the write path: the transcript ingestion pipeline
//! dispatches it once per episode, optionally accompanied by embeddings.
//! [`SearchKnowledge`] is the read path: agent tools and the search UI
//! dispatch it with a precomputed query embedding (embedding generation
//! is provider-side, not policy in this crate).

use serde::{Deserialize, Serialize};

use crate::types::{EmbeddingVector, KnowledgeChunk};

/// Insert (or replace) a batch of chunks for an episode.
///
/// The store de-duplicates by `(episode_id, chunk_index)` so re-ingesting
/// the same transcript replaces rather than accumulates. When
/// `replace_episode` is true the kernel removes every prior chunk for
/// the episode before applying the new ones — used when the transcript
/// segmentation changed (different STT provider, different chunk policy).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct IngestChunks {
    pub episode_id: String,
    pub chunks: Vec<KnowledgeChunk>,
    #[serde(default)]
    pub replace_episode: bool,
}

/// Top-K semantic search against the knowledge store.
///
/// `query_embedding` is the dense vector for the natural-language query —
/// generated by the embedding provider (OpenRouter, Ollama, etc.) before
/// dispatching this action.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SearchKnowledge {
    pub query_embedding: EmbeddingVector,
    pub k: u32,
    /// Optional scope filter: when present, only chunks belonging to one
    /// of these episode IDs are considered. Empty/None means search the
    /// whole store.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub episode_ids: Option<Vec<String>>,
}

#[cfg(test)]
#[path = "actions_tests.rs"]
mod tests;
