import Foundation
import os.log

// MARK: - AgentGeneratedPodcastService
//
// Manages the "Agent Generated" virtual `Podcast` and its on-disk episode
// audio files.
//
// The podcast uses the sentinel feed URL `agent-generated://podcast` and
// `kind: .synthetic` so it is excluded from OPML export, feed-refresh
// scheduling, and the download service's auto-download evaluator. Callers
// branch on `Podcast.kind == .synthetic` rather than comparing URL strings.
//
// The user is NOT auto-subscribed to this podcast — synthetic shows have a
// `Podcast` row but no `PodcastSubscription`. Episodes still appear in the
// library through the normal episode list; the show simply doesn't show up
// in the user's followed-podcasts list.
//
// Audio files live under:
//   Application Support / podcastr / agent-episodes / <episodeID>.m4a
//
// Each call to `publishEpisode` creates a new `Episode` with
// `downloadState = .downloaded` and a `file://` `enclosureURL` pointing at
// the stitched m4a. The player reads local URLs exactly like remote ones
// through the existing AudioEngine local-file fallback.

struct AgentGeneratedPodcastService: Sendable {

    private static let logger = Logger.app("AgentGeneratedPodcastService")

    // MARK: - Sentinel

    /// The sentinel feed URL that identifies the agent-generated virtual
    /// podcast. Never used for HTTP requests.
    static let sentinelFeedURL = URL(string: "agent-generated://podcast")!

    // MARK: - Storage

    /// Root directory for agent-generated episode audio files.
    static func audioDirectory() throws -> URL {
        let support = try FileManager.default.url(
            for: .applicationSupportDirectory,
            in: .userDomainMask,
            appropriateFor: nil,
            create: true
        )
        let dir = support
            .appendingPathComponent("podcastr", isDirectory: true)
            .appendingPathComponent("agent-episodes", isDirectory: true)
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir
    }

    /// Returns the canonical m4a URL for an agent episode by its UUID.
    /// The file need not exist yet — callers write here before calling
    /// `publishEpisode`.
    static func audioFileURL(episodeID: UUID) throws -> URL {
        try audioDirectory().appendingPathComponent("\(episodeID.uuidString).m4a")
    }

    // MARK: - Podcast row management

    /// Returns the existing agent-generated podcast row id, or creates the
    /// row and returns its new id. Safe to call repeatedly — the row is
    /// only inserted once (keyed on `sentinelFeedURL`).
    @MainActor
    static func ensurePodcastID(in store: AppStateStore) -> UUID {
        if let existing = store.podcast(feedURL: sentinelFeedURL) {
            return existing.id
        }
        let podcast = Podcast(
            kind: .synthetic,
            feedURL: sentinelFeedURL,
            title: "Agent Generated",
            author: "Podcast Agent",
            imageURL: nil,
            description: "Episodes generated by your AI agent."
        )
        let stored = store.upsertPodcast(podcast)
        logger.info("Created agent-generated podcast \(stored.id, privacy: .public)")
        return stored.id
    }

    // MARK: - Episode publishing

    /// Registers a finished m4a file as an episode on the agent-generated
    /// podcast and inserts it into `AppStateStore`. The file at `audioURL`
    /// must already exist on disk.
    ///
    /// - Parameter imageURL: Optional artwork to attach directly to the
    ///   episode. The TTS composer passes the source-clip artwork from the
    ///   first snippet chapter so the produced episode has meaningful art
    ///   even though the synthetic podcast itself has none.
    @MainActor
    @discardableResult
    static func publishEpisode(
        title: String,
        description: String,
        audioURL: URL,
        durationSeconds: TimeInterval?,
        imageURL: URL? = nil,
        generationSource: Episode.GenerationSource? = nil,
        targetPodcastID: UUID? = nil,
        in store: AppStateStore
    ) -> Episode {
        let podcastID = targetPodcastID ?? ensurePodcastID(in: store)
        let episodeID = UUID()
        let episode = Episode(
            id: episodeID,
            podcastID: podcastID,
            guid: episodeID.uuidString,
            title: title,
            description: description,
            pubDate: Date(),
            duration: durationSeconds,
            enclosureURL: audioURL,
            enclosureMimeType: "audio/mp4",
            imageURL: imageURL,
            downloadState: .downloaded(
                localFileURL: audioURL,
                byteCount: (try? FileManager.default.attributesOfItem(atPath: audioURL.path)[.size] as? Int64) ?? 0
            ),
            generationSource: generationSource
        )
        store.upsertEpisodes([episode], forPodcast: podcastID, evaluateAutoDownload: false)
        logger.info("Published agent episode '\(title, privacy: .public)' id=\(episodeID, privacy: .public)")
        return episode
    }
}
