//! Per-podcast keypair store for NIP-F4 owned podcast publishing
//! (features #27/#28).
//!
//! Each podcast the user "owns" — i.e. has chosen to publish as a
//! NIP-F4 `kind:10154` show event — gets its own Nostr secret key.
//! The public key derived from it is what appears in the show event,
//! and (collectively) in the user's `kind:10064` author-claim event
//! under the agent identity.
//!
//! ## Scope (PR-only)
//!
//! * In-memory only — disk persistence belongs to the future
//!   `PodcastStore` schema bump (the spec for this PR keeps the keys
//!   here so the unit test round-trip is hermetic).
//! * Pubkey derivation is a **placeholder** (FNV-style hash, mixed
//!   with a salt to make it look pubkey-shaped) — real secp256k1
//!   derivation lands when `nmp-keys` integration is wired through
//!   to per-podcast keys. Marked `TODO(secp256k1)` so it's grep-able.
//!
//! ## D6
//!
//! Every lookup is total: `None` for missing keys, never panics on
//! poisoned mutexes higher up the stack.

use std::collections::HashMap;

use uuid::Uuid;

/// In-memory per-podcast secret-key store.
///
/// Keyed by `podcast_id` (UUID hyphenated string — the same form the
/// FFI `PodcastSummary.id` carries) so the action module can resolve a
/// row purely from the wire payload it received.
#[derive(Default)]
pub struct PodcastKeyStore {
    keys: HashMap<String, [u8; 32]>,
}

impl PodcastKeyStore {
    pub fn new() -> Self {
        Self {
            keys: HashMap::new(),
        }
    }

    /// Generate (or replace) a 32-byte secret key for `podcast_id`.
    /// Returns the freshly-generated bytes so the caller can derive
    /// the pubkey without going back through `get_key`.
    ///
    /// Uses `uuid::Uuid::new_v4()` twice to fill 32 bytes — no new
    /// `rand` dependency, and `Uuid::new_v4` is documented as
    /// cryptographically random on every supported platform.
    pub fn generate_key(&mut self, podcast_id: &str) -> [u8; 32] {
        let a = Uuid::new_v4().into_bytes();
        let b = Uuid::new_v4().into_bytes();
        let mut bytes = [0u8; 32];
        bytes[..16].copy_from_slice(&a);
        bytes[16..].copy_from_slice(&b);
        self.keys.insert(podcast_id.to_owned(), bytes);
        bytes
    }

    pub fn get_key(&self, podcast_id: &str) -> Option<&[u8; 32]> {
        self.keys.get(podcast_id)
    }

    pub fn remove_key(&mut self, podcast_id: &str) {
        self.keys.remove(podcast_id);
    }

    /// Public key derived from the stored secret key for `podcast_id`.
    ///
    /// **TODO(secp256k1):** real secp256k1 derivation. Currently a
    /// deterministic placeholder hash so the FFI smoke test can assert
    /// "different secret → different pubkey" without pulling in a
    /// heavy crypto dependency just for this stub.
    pub fn pubkey_hex(&self, podcast_id: &str) -> Option<String> {
        self.keys.get(podcast_id).map(|sk| derive_pubkey_hex(sk))
    }

    /// Iterator over `(podcast_id, pubkey_hex)` for every key currently
    /// known to the store. Used by the snapshot builder to populate
    /// `PodcastUpdate.owned_podcasts` and by `publish_author_claim`
    /// to enumerate `p` tags.
    pub fn iter_pubkeys(&self) -> Vec<(String, String)> {
        self.keys
            .iter()
            .map(|(id, sk)| (id.clone(), derive_pubkey_hex(sk)))
            .collect()
    }
}

/// FNV-1a-style 256-bit fold of the secret key. Deterministic so the
/// same secret round-trips to the same pubkey across snapshot ticks;
/// avalanche-y enough that two different secrets produce different
/// pubkeys with overwhelming probability.
///
/// **TODO(secp256k1):** replace with real secp256k1 x-only public-key
/// derivation once `nmp-keys` exposes a per-podcast keypair API.
fn derive_pubkey_hex(sk: &[u8; 32]) -> String {
    // Two independent FNV-1a streams seeded with distinct constants so
    // a single byte flip propagates across the whole 32-byte output.
    let mut state: [u64; 4] = [
        0xcbf29ce4_84222325, // FNV offset basis (standard)
        0x84222325_cbf29ce4, // byte-swapped offset
        0xfb147f3a_1c2b8d99, // arbitrary, fixed
        0x1c2b8d99_fb147f3a, // byte-swapped of the above
    ];
    const PRIME: u64 = 0x00000100_000001B3;
    for (i, byte) in sk.iter().enumerate() {
        let lane = i % 4;
        state[lane] ^= *byte as u64;
        state[lane] = state[lane].wrapping_mul(PRIME);
        // Cross-lane mix so the four lanes don't drift independently.
        state[(lane + 1) % 4] = state[(lane + 1) % 4].wrapping_add(state[lane]);
    }
    let mut out = String::with_capacity(64);
    for lane in &state {
        out.push_str(&format!("{:016x}", lane));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_key_returns_32_bytes_and_stores_them() {
        let mut store = PodcastKeyStore::new();
        let sk = store.generate_key("pod-1");
        assert_eq!(sk.len(), 32);
        let fetched = store.get_key("pod-1").expect("stored");
        assert_eq!(fetched, &sk);
    }

    #[test]
    fn pubkey_hex_is_64_chars_lowercase_hex() {
        let mut store = PodcastKeyStore::new();
        store.generate_key("pod-1");
        let pk = store.pubkey_hex("pod-1").expect("derived");
        assert_eq!(pk.len(), 64);
        assert!(pk.chars().all(|c| c.is_ascii_hexdigit() && !c.is_ascii_uppercase()));
    }

    #[test]
    fn pubkey_hex_is_deterministic_per_secret() {
        let mut store_a = PodcastKeyStore::new();
        let mut store_b = PodcastKeyStore::new();
        let sk = store_a.generate_key("pod-1");
        // Inject the same secret into a second store to compare.
        store_b.keys.insert("pod-1".into(), sk);
        assert_eq!(store_a.pubkey_hex("pod-1"), store_b.pubkey_hex("pod-1"));
    }

    #[test]
    fn different_secrets_produce_different_pubkeys() {
        let mut store = PodcastKeyStore::new();
        store.generate_key("pod-a");
        store.generate_key("pod-b");
        let a = store.pubkey_hex("pod-a").expect("a");
        let b = store.pubkey_hex("pod-b").expect("b");
        // 256 bits of state; collision probability is astronomical.
        assert_ne!(a, b);
    }

    #[test]
    fn remove_key_clears_lookup() {
        let mut store = PodcastKeyStore::new();
        store.generate_key("pod-1");
        store.remove_key("pod-1");
        assert!(store.get_key("pod-1").is_none());
        assert!(store.pubkey_hex("pod-1").is_none());
    }

    #[test]
    fn generate_key_overwrites_existing() {
        let mut store = PodcastKeyStore::new();
        let first = store.generate_key("pod-1");
        let second = store.generate_key("pod-1");
        // Replaces; the second value is what's now stored.
        assert_eq!(store.get_key("pod-1"), Some(&second));
        // And the two generated values differ (UUID v4 random).
        assert_ne!(first, second);
    }

    #[test]
    fn iter_pubkeys_returns_every_known_podcast() {
        let mut store = PodcastKeyStore::new();
        store.generate_key("pod-a");
        store.generate_key("pod-b");
        let mut pairs = store.iter_pubkeys();
        pairs.sort_by(|a, b| a.0.cmp(&b.0));
        assert_eq!(pairs.len(), 2);
        assert_eq!(pairs[0].0, "pod-a");
        assert_eq!(pairs[1].0, "pod-b");
        assert_ne!(pairs[0].1, pairs[1].1);
    }

    #[test]
    fn get_key_returns_none_for_unknown_podcast() {
        let store = PodcastKeyStore::new();
        assert!(store.get_key("never-generated").is_none());
        assert!(store.pubkey_hex("never-generated").is_none());
    }
}
