import XCTest
@testable import Podcastr

/// Cross-language wire-contract guard for the kernel-owned widget projection.
///
/// WHY THIS EXISTS: PR #366 embedded a `WidgetSnapshot` in `PodcastUpdate` with
/// explicit snake_case `CodingKeys`. The bridge decodes `PodcastUpdate` with
/// `keyDecodingStrategy = .convertFromSnakeCase`, which rewrites wire keys
/// (`is_playing` → `isPlaying`) BEFORE key lookup — so the explicit snake_case
/// keys matched nothing, the required `isPlaying` threw `keyNotFound`, and the
/// ENTIRE `PodcastUpdate` decode failed on every push/pull frame. The library
/// froze at "No episodes yet" in the live simulator. The existing
/// `PlatformWidgetSnapshotTests` missed it because they round-tripped
/// Swift-encoded JSON, never RUST-encoded JSON through the bridge's decoder.
///
/// This test closes that gap: it decodes a **Rust-emitted** `PodcastUpdate`
/// fixture (`tests/fixtures/podcast_update_with_widget.json`, generated by the
/// Rust `podcast_update_with_widget_matches_fixture` test from real serde
/// output) through the **exact** bridge decode seam (`KernelDecoding`). If the
/// embedded widget — or any other field — ever stops decoding under the bridge
/// config, this fails instead of the live app.
final class PlatformWidgetContractTests: XCTestCase {

    private func loadFixture() throws -> Data {
        let bundle = Bundle(for: Self.self)
        guard let url = bundle.url(
            forResource: "podcast_update_with_widget", withExtension: "json")
        else {
            XCTFail("podcast_update_with_widget.json missing from test bundle — check Project.swift resources")
            return Data()
        }
        return try Data(contentsOf: url)
    }

    /// The whole frame decodes through the bridge seam — the embedded widget
    /// must NOT torpedo the decode (the #366 failure mode).
    func testRustPodcastUpdateFixtureDecodesThroughBridgeSeam() throws {
        let data = try loadFixture()
        // Decodes via the SAME path the bridge uses in production.
        let update = try KernelDecoding.decodePodcastUpdate(from: data)

        // The library survives (the regression left this empty).
        XCTAssertEqual(update.library.count, 1)
        XCTAssertEqual(update.library.first?.title, "The Daily")
        XCTAssertEqual(update.library.first?.episodes.first?.title, "The Daily — Friday")

        // The embedded widget decodes fully — every field, including the
        // required `isPlaying` that previously threw.
        let widget = try XCTUnwrap(update.widget, "widget must decode, not be dropped to nil")
        XCTAssertEqual(widget.nowPlayingEpisodeTitle, "The Daily — Friday")
        XCTAssertEqual(widget.nowPlayingPodcastTitle, "The Daily")
        XCTAssertEqual(widget.nowPlayingArtworkUrl, "https://ex.com/ep.png")
        XCTAssertEqual(widget.nowPlayingChapterTitle, "Headlines")
        XCTAssertTrue(widget.isPlaying)
        XCTAssertEqual(widget.positionFraction, 0.25)
        XCTAssertEqual(widget.positionSecs, 300.0)
        XCTAssertEqual(widget.durationSecs, 1200.0)
        XCTAssertEqual(widget.unplayedCount, 5)
    }

    /// Pin the failure mode precisely: decoding the same Rust fixture with a
    /// PLAIN decoder (no snake_case conversion) must fail, proving the bridge's
    /// `.convertFromSnakeCase` config is load-bearing for this frame.
    func testPlainDecoderFailsOnRustFixture() throws {
        let data = try loadFixture()
        XCTAssertThrowsError(
            try JSONDecoder().decode(PodcastUpdate.self, from: data),
            "A plain decoder must fail on the snake_case Rust frame; if it succeeds, "
                + "the wire shape or decoder config changed — re-audit the bridge."
        )
    }
}
